### ISSUE TITLE
Parallelism problem: single caller to multiple OPE instances of model 

### ISSUE THREAD

**Issue by vkuzmin-uber** [uber/neuropod#336]
I tested parallelism ability for multiple instances of the same model. Goal was to see if RPS/Bandwidth can be increased using multiple OPE instances of model. This is especially interesting for Python models that have GIL per process.

In short, I observe parallelism and see benefits of "parallel" approach when model has heavy inference.

But, I observed some unexpected behavior and was able to demonstrate it with "single caller to multiple OPE instances of model".

Description:
1) Load 8 or more models of "String Python" model that accepts "str_input" string and returns it as "str_output" string.
2) Use caller of Inference with concurrency 1  (only 1 thread executes 1 inference at the moment).

*Test 1*
Caller calls 20K inference of one model instances always (first model with index 0):
Call 0
Call 0
...
Call 0

Result, ElapsedTime=7.669s, RPS=2607.86

Algorithm/Code
```
// Note that it performs "round-robin" index calculation and only then reset it to 0
func (p *modelProxy) Infer(request) {
	modelIndex := p.currentIndex.increment() % int32(len(p.instances))
	if modelIndex > 0 {
		modelIndex = 0
	}
	instance := p.instances[modelIndex]
	return instance.Infer(request)
}
```

Details: 
```
Benchmark parameters:
  CPUs:            12
  Connections:     1
  Concurrency:     1
  Max requests:    20000
  Max duration:    0s
  Max RPS:         0
Latencies:
  0.5000: 338.51µs
  0.9000: 402.814µs
  0.9500: 442.647µs
  0.9900: 578.288µs
  0.9990: 838.394µs
  0.9995: 972.958µs
  1.0000: 5.465745ms
Elapsed time:      7.669s
Total requests:    20000
RPS:               2607.86
```

*Test 2*
Caller calls 20K inference of model instances using Round-Robin strategy.
Call 0
Call 1
...
Call 8
Call 0

Result, ElapsedTime=1m43.279s, RPS=193.65

Algorithm/Code
```

// Note that it performs "round-robin" index calculation using sync/atomic 
func (p *modelProxy) Infer(request) {
	modelIndex := p.currentIndex.increment() % int32(len(p.instances))
	instance := p.instances[modelIndex]
	return instance.Infer(request)
}
```

Details:
```
Benchmark parameters:
  CPUs:            12
  Connections:     1
  Concurrency:     1
  Max requests:    20000
  Max duration:    0s
  Max RPS:         0
Latencies:
  0.5000: 5.38258ms
  0.9000: 6.242816ms
  0.9500: 6.265063ms
  0.9900: 6.425146ms
  0.9990: 6.946838ms
  0.9995: 27.727982ms
  1.0000: 39.07278ms
Elapsed time:      1m43.279s
Total requests:    20000
RPS:               193.65
```

You may see that Test 2 ten times slower than Test 1 that is not expected. It looks that Caller thread from "master" process performs some expensive "reset" every time it calls a new instances of model.

Note that with caller concurrency >1 it RPS is increasing. So, this is important to use concurrency 1 to reproduces it.

**Comment by vkuzmin-uber** [comment]
I had a chance today to test at Linux and I still observer the problem that more instances of the same models and load balancing between them reduces performance:

```
(env)vkuzmin@adhoc22-dca1:~/neuropod_test$ time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 1 100000
instanceNumber=1 requestNumber=100000
06/09/20 22:43:03.592457: W neuropod/internal/cuda_device_mapping.cc:235] [thread 52482, process 52482] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID

real	0m18.898s
user	0m18.415s
sys	0m9.785s
(env)vkuzmin@adhoc22-dca1:~/neuropod_test$ time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 2 100000
instanceNumber=2 requestNumber=100000
06/09/20 22:44:39.477229: W neuropod/internal/cuda_device_mapping.cc:235] [thread 54217, process 54217] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:44:39.633244: W neuropod/internal/cuda_device_mapping.cc:235] [thread 54217, process 54217] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID

real	0m30.439s
user	0m29.976s
sys	0m16.382s

(env)vkuzmin@adhoc22-dca1:~/neuropod_test$ time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 8 100000
instanceNumber=8 requestNumber=100000
06/09/20 22:47:07.440684: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:07.596723: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:07.724951: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:07.930114: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:08.087754: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:08.264947: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:08.429434: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:47:08.574065: W neuropod/internal/cuda_device_mapping.cc:235] [thread 57205, process 57205] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID

real	0m44.272s
user	0m48.698s
sys	0m32.074s
```

This is not bad as at OSX but still I expect that execution time is the same excluding time spent on initialization.

And I see that if I use the same number if instances but send all requests to instance with index 0, there is no this problem

This is result of 8 instances but all requests are sent to model 0, it is comparable with result when only 1 instance is used 
```
(env)vkuzmin@adhoc22-dca1:~/neuropod_test$ time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 8 100000
instanceNumber=8 requestNumber=100000
06/09/20 22:50:47.917437: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.072553: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.247527: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.433294: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.570340: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.761939: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:48.959004: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID
06/09/20 22:50:49.149515: W neuropod/internal/cuda_device_mapping.cc:235] [thread 61480, process 61480] Didn't find a GPU corresponding to the requested CUDA ID 0. Returning empty UUID

real	0m19.970s
user	0m27.111s
sys	0m23.197s
```

It means that there is some performance hit in IPC when we do a load balancing between models.

**Comment by vkuzmin-uber** [comment]
Updated test program:

Build
```
g++ -O3 -std=c++11 -Iinclude -Llib -lneuropod main.cc
```
Run
```
time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 1 100000
time PATH=$PATH:bin/ LD_LIBRARY_PATH=lib ./a.out 8 100000
```

Source code
```
#include <iostream>
#include <string>
#include <vector>

#include <neuropod/neuropod.hh>

int main(int argc, char* argv[]) {
   unsigned long instanceNumber = 1;
   if (argc >= 2) {
      instanceNumber = std::stoul(argv[1]);
   }

   unsigned long requestNumber = 10;
   if (argc >= 3) {
      requestNumber = std::stoul(argv[2]);
   }


   std::cout << "instanceNumber=" << instanceNumber
             << " requestNumber=" << requestNumber << std::endl;

   // Create models
   std::vector<neuropod::Neuropod> models;
   for (unsigned long i = 0; i < instanceNumber; ++i)
   {
      neuropod::RuntimeOptions opts;
      opts.use_ope = true;
      models.emplace_back("example/string_python/neuropod/", opts);
   }

   size_t counter = 0;
   size_t num_models = models.size();
   for (size_t i = 0; i < requestNumber; ++i)
   {
      // Simple round robin
      auto &neuropod = models.at(counter);
      counter        = (counter + 1) % num_models;

      neuropod::NeuropodValueMap input_data;

      // Add an input "str_input"
      auto tensor = neuropod.allocate_tensor<std::string>({1, 1});
      std::vector<std::string> vec;
      vec.push_back("benchmark");
      tensor->copy_from(vec);
      input_data["str_input"] = tensor;

      // Run inference
      const auto output_data = neuropod.infer(input_data);
   }

   return 0;
}
```

**Comment by thuningxu** [comment]
What if you call neuropod.infer() from different threads? Your current set up does not send parallel requests, and hence at any time only one neuropod instance is running.

**Comment by vkuzmin-uber** [comment]
> What if you call neuropod.infer() from different threads? Your current set up does not send parallel requests, and hence at any time only one neuropod instance is running.

This is how I originally discovered problem. 

We have a Go Protobuf service that has Inference Request handler. Execution is concurrent, every request is handled by separate thread. It is know that Python models has a GIL. Using OPE and multiple instances with load balancing between models should demonstrate better performance because OPE means no shared GIL between worker instances.

The example I published above is a try to narrow problem and demonstrate this is a problem namely of multiple instance and load balancing between them.

**Comment by vkuzmin-uber** [comment]
@thuningxu about 0.2ms, my concern is that this is not simple O(1) overhead.
In practice we probably are going to use 1-4 instances for load balancing:

I updated code of test I published aboe. Now it reports RPS of inference part only w/o init/exit.  Look at RPS

instanceNumber=1 requestNumber=1000 generateUniqueValue=true useIndex=-1 duration=173990 rps=5747.46 

instanceNumber=2 requestNumber=1000 generateUniqueValue=true useIndex=-1 duration=230493 rps=4338.53

instanceNumber=3 requestNumber=1000 generateUniqueValue=true useIndex=-1 duration=314903 rps=3175.58

instanceNumber=4 requestNumber=1000 generateUniqueValue=true useIndex=-1 duration=346399 rps=2886.84

It looks that RPS depends on number of instances/worker processes. I'd like to understand it better. 

Vivek mentioned good ideas about stats and CPU frequency scaling, I will take it in account. 

Profiling of "main.cc" and its stats don't show helpful details (especially without complier optimization).  Inference execution happens inside neuropod libs and worker process and its profiling can be useful.

Will update here if find any details.

**Comment by VivekPanyam** [comment]
@vkuzmin-uber I'm going to close this issue because:

- the behavior you see seems reasonable given cache misses, branch mispredictions, etc (based on the profiling I explained in my comment above)
- the benchmark doesn't appear to be measuring something we care about 
- there hasn't been activity on this issue for > 3 months

Again, see my last comment above (https://github.com/uber/neuropod/issues/336#issuecomment-642263251) for suggested next steps (especially the "What you're trying to measure" section).

Feel free to reopen if necessary.
