### ISSUE TITLE
ValueError: Expected requirements of the form name==version but got --index-url

### ISSUE THREAD

**Issue by qiyanz** [uber/neuropod#479]
## Bug

Deeplearning Inference could not pass the local test for models and got the following error

`LoadNeuropod modelPath = ./example/torch_addition/neuropod failed: ValueError: Expected requirements of the form name==version but got --index-url`

## To Reproduce

1. Run the command that tests c_model in the terminal with neuropod 0.3.0 rc

## Expected behavior

All tests could pass

## Environment

 - Neuropod Version: 0.3.0rc
 - OS:macOS
 - Language: Python
 - Python version: 2.7
 - Using OPE: no
 
If this bug report is about running a specific model:

 - Neuropod backend (e.g. TensorFlow, PyTorch, Keras, TorchScript, Python): PyTorch
 - Framework version (e.g. 1.3.0): 1.4

If running on GPU: No

 - CUDA/cuDNN version:
 - The output of `nvidia-smi`:
 ```
 
 ```
 
 - Any other relevant information:

**Comment by VivekPanyam** [comment]
As we talked about offline, the solution will probably be to add `--no-emit-index-url` and possibly other flags to

https://github.com/uber/neuropod/blob/ca7e3b8b97b6ca4cb8bab0f5267bdd7f8215583f/source/python/neuropod/utils/pip_utils.py#L24-L37

**Comment by VivekPanyam** [comment]
Closed by #480. Thanks for the PR!
