### ISSUE TITLE
Slicing is not done correctly for torch script model

### ISSUE THREAD

**Issue by irasit** [uber/neuropod#553]
## Bug

Model graph definition and test case can be found [here](https://sourcegraph.uberinternal.com/code.uber.internal/data/ml-code@pengz_debug_neuropod_oneoff/-/blob/data/michelangelo/app_framework/steps/trainer/lightning_estimator_trainer_test.py#L158)
Full test output can be found in [here](https://code.uberinternal.com/P323023)

Observations:
1. using the same input, output of torch script is:
oov_score candidate_1_loc_score candidate_2_loc_score candidate_3_loc_score max_dt_score max_dt_idx
-1.5255 -1.8325 -1.1476 -1.1872 -1.1476 2
-1.8007 -2.1059 -0.6945 -1.5428 -0.6945 2
-1.7837 -2.1038 -0.6955 -1.555 -0.6955 2
-1.7096 -2.1034 -0.6809 -1.6561 -0.6809 2
-1.782 -1.9525 -0.7757 -1.4723 -0.7757 2

2. after do change the model to neuropod, the output changed to
oov_score candidate_1_loc_score candidate_2_loc_score candidate_3_loc_score max_dt_score max_dt_idx
-1.5255 -1.8325 -1.1476 -1.1872 -1.1476 2
-1.8325 -1.1476 -1.1872 -1.8007 -0.6945 2
-1.1476 -1.1872 -1.8007 -2.1059 -0.6955 2
-1.1872 -1.8007 -2.1059 -0.6945 -0.6809 2
-1.8007 -2.1059 -0.6945 -1.5428 -0.7757 2

3. Each row in output should be independent, but instead, the value of first 4 features are copying last row with 1 value shift. and last 2 features are correct without any change.

4. The first 4 columns "oov_score candidate_1_loc_score candidate_2_loc_score candidate_3_loc_score" are coming from values in a same metrics.
oov_score = torch.reshape(scores[:, 0], (-1, 1)),
candidate_1_loc_score = torch.reshape(scores[:, 1], (-1, 1)),
candidate_2_loc_score = torch.reshape(scores[:, 2], (-1, 1)),
candidate_3_loc_score= torch.reshape(scores[:, 3], (-1, 1)),

5. Seems there are some issue in neuropod core to unpack the columns from a tensor.

6. The result of column "max_dt_score" and "max_dt_idx" is correct, so it dose not seems a model level config issue. 

Suspections:
Is it possible that Neuropod slicing step (e.g `scores[:, i]`) puts the prediction output results in some kind of buffer, and we are not moving the buffer pointer correctly.
For example:
Assume the `scores` tensor is something like:
row 1 is [A1, B1, C1, D1]
row 2 is [A2, B2, C2, D2]
row 3 is [A3, B3, C3, D3]
row 4 is [A4, B4, C4, D4]
In Neuropod core, it may save the tensor in some memory block like :
    [A1, B1, C1, D1, A2, B2, C2, D2, A3, B3, C3, D3, A4, B4, C4, D4]
When we do `scores[:, 1]`, 
expect it to move pointer like `i*4 + 1 ` and get [B1, B2, B3, B4],
but instead it is doing` i + 1 ` and send back [B1, C1, D1, A2]

## OS and Verison
Both MacOS and Linux
Version: 
  "https://github.com/uber/neuropod/releases/download/v0.3.0-rc6/libneuropod-cpu-macos-v0.3.0-rc6-torchscript-1.7.0-backend.tar.gz"
  "https://github.com/uber/neuropod/releases/download/v0.3.0-rc6/libneuropod-cpu-macos-v0.3.0-rc6-python-36-backend.tar.gz"

**Comment by VivekPanyam** [comment]
Thanks for the issue. I have a hypothesis on what's causing the problem. When you return the `scores` tensor from your model, can you make it contiguous?

So instead of something like

```py
def forward(...):
    # ...

    return {
        "scores": scores_tensor
    }
```

do something like this instead:

```py
def forward(...):
    # ...

    return {
        "scores": scores_tensor.contiguous()
    }
```

If that fixes the problem, then we can put a fix into Neuropod.

Also, when creating an issue, please include things that were specified in the issue template (e.g. OS, framework version, Neuropod version, etc.). Thanks!

**Comment by VivekPanyam** [comment]
Ah you need a `.contiguous()` after the reshapes.

So
```
def forward(...):

            return output_tuple(
                torch.reshape(scores[:, 0], (-1, 1)).contiguous(),
                torch.reshape(scores[:, 1], (-1, 1)).contiguous(),
                torch.reshape(scores[:, 2], (-1, 1)).contiguous(),
                torch.reshape(scores[:, 3], (-1, 1)).contiguous(),
                max_dt_score,
                max_dt_idx.float()
            )
```

**Comment by irasit** [comment]
After changed with above workaround, the issue seems fixed. 
the neuropod output is now consistent with what torchscirpt has. 

oov_score	candidate_1_loc_score	candidate_2_loc_score	candidate_3_loc_score	max_dt_score	max_dt_idx
-1.876510739326477	-0.48913267254829407	-2.256047010421753	-2.0482935905456543	-0.48913267254829407	1.0
-1.8580975532531738	-0.4892353117465973	-2.2592461109161377	-2.0674595832824707	-0.4892353117465973	1.0
-1.7892135381698608	-0.5119701623916626	-2.269895076751709	-2.038132667541504	-0.5119701623916626	1.0
-1.8107632398605347	-0.6201655864715576	-1.9938052892684937	-1.81745183467865	-0.6201655864715576	1.0
-1.9136452674865723	-0.6040871143341064	-2.147082567214966	-1.6656864881515503	-0.6040871143341064	1.0

scores=-1.8765 -0.4891 -2.2560 -2.0483
-1.8581 -0.4892 -2.2592 -2.0675
-1.7892 -0.5120 -2.2699 -2.0381
-1.8108 -0.6202 -1.9938 -1.8175
-1.9136 -0.6041 -2.1471 -1.6657

**Comment by irasit** [comment]
@VivekPanyam Thank you so much for the root causing and fixing it !
